config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  get 'pages/about'

  get 'pages/contact'

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def index
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(params.require(:restaurant).permit(:name, :street, :city, :state, :phone, :email, :image))

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: "Restaurant saved" }
      else
        format.html { render :new }
      end
    end
  end

  def index
    @restaurant = Restaurant.all
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end


end

private

def find_restaurant
  @restaurant = Restaurant.find(params[:id])
end

def restaurant_params
  params.require(:restaurant).permit(:name, :street, :phone, :email, :image)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="widget widget-about">
          <div class="logo-ft">
            <%= link_to "Two Cents", root_path %>
          </div>
          <p>
            This app was built <br/> with Ruby on Rails!
          </p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="widget widget-contact">
          <h3 class="widget-title">Contact</h3>
          <ul class="contact-infomation">
            <li class="address">
              Dallas, TX
            </li>
            <li class="phone">
              (682) 220-2537
            </li>
            <li class="email">
              jay.m.howard@gmail.com
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

<div class="footer-bottom">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="copyright">
          © 2018 Monica Howard | All rights reserved.
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="header">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="header-wrap">
          <div id="logo" class="logo">
            <%= link_to "Two Cents App", root_path %>
          </div>

          <div class="nav-wrap">
            <nav id="mainnav" class="mainnav">
              <ul class="menu">
                <li>
                  <%= link_to "Restaurants" %>
                  <ul class="submenu">
                    <li>
                      <%= link_to "View All Restaurants", restaurants_path %>
                    </li>
                    <li>
                      <%= link_to "Add New Restaurant", new_restaurant_path %>
                    </li>
                  </ul>
                </li>
                <li>
                  <%= link_to "Explore" %>
                  <ul class="submenu">
                    <li>
                      <%= link_to "About", pages_about_path %>
                    </li>
                    <li>
                      <%= link_to "Contact", pages_contact_path %>
                    </li>
                  </ul>
                </li>
              </ul>
            </nav>

            <div class="button-header">
              <%= link_to "Add A New Restaurant", new_restaurant_path, class: "ti-plus" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>TwoCentsReviewApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="header_sticky">

    <%= render "layouts/nav" %>

    <%= yield %>

    <%= render "layouts/footer" %>

  </body>
</html>

app/views/pages/about.html.erb
<section class="page-title parallax parallax1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="page-title-heading">
          About Me
        </div>
        <ul class="breadcrumbs">
          <li>
            <%= link_to "Home", root_path %>
            <span class="arrow_right"></span>
          </li>
          <li>
            About Me
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="overlay"></div>
</section><

<section class="flat-row main-single">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <article class="post-single">
          <div class="entry-post">
            <div class="entry-header">
              <h2 class="entry-title">"Creating visually-pleasing, highly functional Rails apps is my passion"</h2>
              <p> - Monica Howard</p>
            </div>
            <div class="entry-content">
              <div class="entry-answer">
                <p class="question ">
                  I created this website with Ruby on Rails!
                </p>
              </div>
            </div>
          </div>
        </article>
      </div>
    </div>
  </div>
</section>

app/views/pages/contact.html.erb
<section class="page-title parallax parallax1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="page-title-heading">
          Contact Me
        </div>
        <ul class="breadcrumbs">
          <li>
            <%= link_to "Home" %>
            <span class="arrow_right"></span>
          </li>
          <li>
            <%= link_to "Contact", pages_contact_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="overlay"></div>
</section>

<section class="flat-row flat-iconbox style2">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <div class="iconbox-item">
          <div class="iconbox style2">
            <div class="box-header">
              <div class="iconbox-icon">
                <%= image_tag "page/address.png" %>
              </div>
            </div>
            <div class="box-content">
              <div class="box-desc">
                <p>Dallas, TX</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="iconbox-item">
          <div class="iconbox style2">
            <div class="box-header">
              <div class="iconbox-icon">
                <%= image_tag "page/email.png" %>
              </div>
            </div>
            <div class="box-content">
              <div class="box-desc">
                <p>MonicaHoward.net</p>
                <p>jay.m.howard@gmail.com</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="iconbox-item">
          <div class="iconbox style2">
            <div class="box-header">
              <div class="iconbox-icon">
                <<%= image_tag "page/phone.png" %>
              </div>
            </div>
            <div class="box-content">
              <div class="box-desc">
                <p>682.220.2537</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="flat-contact">
  <div class="contact-map">
  <%= image_tag "https://images.pexels.com/photos/509922/pexels-photo-509922.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" %>
  </div>
  <div class="contact-form parallax parallax1">
    <div class="contact-us">
      <h3>Contact Me</h3>
      <form action="#" method="get" accept-charset="utf-8">
        <div class="wrap-contact name">
          <input type="text" class="your-name" placeholder="Your name" name="yourname">
        </div>
        <div class="wrap-contact email">
          <input type="email" class="your-email" placeholder="Your email" name="youremail">
        </div>
        <div class="wrap-contact message">
          <textarea class="you-message" placeholder="Your message"></textarea>
        </div>
        <div class="btn-more">
          <a href="#" title="">Send message</a>
        </div>
      </form>
    </div>
    <div class="overlay"></div>
  </div><
  <div class="clearfix"></div>
</section>

app/views/pages/index.html.erb
<section class="page-title style2 parallax parallax1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="page-title-heading">
          Discover the Best Places
        </div>
        <div class="text-heading">
          Find food fast
        </div>
      </div>
    </div>
  </div>
  <div class="overlay"></div>
</section>

<section class="flat-highlights">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="highlights">
          <ul class="menu-list">
            <li>
              <a href="#" title="">
                <img src="images/page/cutlery.png" alt="">
                <span>Pizza</span>
              </a>

            </li>
            <li>
              <a href="#" title="">
                <img src="images/page/double-bed.png" alt="">
                <span>Hamburgers</span>
              </a>

            </li>
            <li class="active">
              <a href="#" title="">
                <img src="images/page/guitar.png" alt="">
                <span>Sushi</span>
              </a>

            </li>
            <li>
              <a href="#" title="">
                <img src="images/page/rent-a-car.png" alt="">
                <span>Buffet</span>
              </a>

            </li>
            <li>
              <a href="#" title="">
                <img src="images/page/shopping-bag.png" alt="">
                <span>Chicken</span>
              </a>

            </li>
            <li>
              <a href="#" title="">
                <img src="images/page/dumbbell.png" alt="">
                <span>Steak House</span>
              </a>

            </li>
            <li>
              <a href="#" title="">
                <img src="images/page/cocktail.png" alt="">
                <span>Mexican</span>
              </a>

            </li>
            <li>
              <a href="#" title="">
                <img src="images/page/park.png" alt="">
                <span>Other</span>
              </a>

            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="flat-row flat-imagebox background">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="flat-row-title center">
          <h2>Browse the Latest Listings</h2>
          <p>
            Choose from the best of the best
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="imagebox">
          <div class="box-imagebox">
            <div class="box-header">
              <div class="box-image">
                <img src="images/page/img-01.png" alt="">
                <a href="#" title="">Preview</a>
                <div class="overlay"></div>
                <div class="queue">
                  <i class="fa fa-star" aria-hidden="true"></i>
                  <i class="fa fa-star" aria-hidden="true"></i>
                  <i class="fa fa-star" aria-hidden="true"></i>
                  <i class="fa fa-star" aria-hidden="true"></i>
                  <i class="fa fa-star-half-o" aria-hidden="true"></i>
                </div>
              </div>
            </div>
            <div class="box-content">
              <div class="box-title ad">
                <span>Ad</span><a href="#" title="">AN Restaurant</a><i class="fa fa-check-circle" aria-hidden="true"></i>
              </div>
              <ul class="rating">
                <li>5 rating</li>
                <li>Moderate</li>
                <li>Restaurant</li>
              </ul>
              <div class="box-desc">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </div>
            </div>
            <ul class="location">
              <li class="address"><span class="ti-location-pin"></span>Hanoi, Vietnam</li>
              <li class="closed">Closed Now !</li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="imagebox">
          <div class="box-imagebox">
            <div class="box-header">
              <div class="box-image">
                <img src="images/page/img-02.png" alt="">
                <a href="#" title="">Preview</a>
                <div class="overlay"></div>
                <div class="queue">
                  <i class="fa fa-star" aria-hidden="true"></i>
                  <i class="fa fa-star" aria-hidden="true"></i>
                  <i class="fa fa-star" aria-hidden="true"></i>
                  <i class="fa fa-star" aria-hidden="true"></i>
                  <i class="fa fa-star" aria-hidden="true"></i>
                </div>
              </div>
            </div>
            <div class="box-content">
              <div class="box-title">
                <a href="#" title="">Acantara</a><i class="fa fa-check-circle" aria-hidden="true"></i>
              </div>
              <ul class="rating">
                <li>10 rating</li>
                <li>Ultra High End</li>
                <li>Hotel</li>
              </ul>
              <div class="box-desc">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </div>
            </div>
            <ul class="location">
              <li class="address"><span class="ti-location-pin"></span>Seoul, Korea</li>
              <li class="open">Open Now !</li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="imagebox">
          <div class="box-imagebox">
            <div class="box-header">
              <div class="box-image">
                <img src="images/page/img-03.png" alt="">
                <a href="#" title="">Preview</a>
                <div class="overlay"></div>
                <div class="queue">
                  <i class="fa fa-star" aria-hidden="true"></i>
                  <i class="fa fa-star" aria-hidden="true"></i>
                  <i class="fa fa-star" aria-hidden="true"></i>
                  <i class="fa fa-star" aria-hidden="true"></i>
                  <i class="fa fa-star" aria-hidden="true"></i>
                </div>
              </div>
            </div>
            <div class="box-content">
              <div class="box-title">
                <a href="#" title="">Intercontinental</a><i class="fa fa-check-circle" aria-hidden="true"></i>
              </div>
              <ul class="rating">
                <li>6 rating</li>
                <li>Pricey</li>
                <li>Hotel</li>
              </ul>
              <div class="box-desc">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </div>
            </div>
            <ul class="location">
              <li class="address"><span class="ti-location-pin"></span>Seoul, Korea</li>
              <li class="open">Open Now !</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="flat-row flat-text-title">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="text-title center">
          <h2>
            Satisfy Your Craving
          </h2>
        </div>
      </div>
    </div>
  </div>
</section>



<section class="flat-row flat-subscribe">
  <div class="container">
    <div class="row">
      <div class="col-sm-7">
        <div class="subscribe-text">
          Subscribe and be notified about new locations
        </div>
      </div>
      <div class="col-sm-5">
        <div class="subscribe-form">
          <form action="#" method="get" accept-charset="utf-8">
            <div class="subscribe-content">
              <div class="input-field">
                <input type="email" name="yourEmail" placeholder="Your Email" />
              </div>
              <button><span class="arrow_right"></span></button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant, :html => { multipart: true }) do |f| %>
  <div class="wrap-listing your-email">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="wrap-listing your-email">
    <%= f.label :street %>
    <%= f.text_field :street, class: "" %>

    <%= f.label :suite %>
    <%= f.text_field :suite %>
  </div>

  <div class="wrap-listing your-email">
    <%= f.label :city %>
    <%= f.text_field :city %>

    <%= f.label :state %>
    <%= f.text_field :state %>

    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div class="wrap-listing your-email">
    <%= f.label :phone %>
    <%= f.text_field :phone %>

    <%= f.label "Website" %>
    <%= f.text_field :email %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_listing.html.erb
<div class="col-sm-12">
  <div class="imagebox style2">
    <div class="box-imagebox">
      <div class="box-header">
        <div class="box-image">
          <%= image_tag @restaurant.image.url unless @restaurant.image.blank? %>
          <%= link_to "Preview", @restaurant_path %>
        </div>
      </div><!-- /.box-header -->
      <div class="box-content">
        <div class="box-title ad">
          <%= link_to "#{@restaurant.name}", restaurant_path %>
        </div>
        <ul class="rating">
          <li>5 rating</li>
          <li>Moderate</li>
          <li>Restaurant</li>
        </ul>
        <div class="box-desc">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        </div>
        <ul class="location">
          <li class="address"><span class="ti-location-pin"></span>#{@restaurant.city}, #{restaurant.state}</li>
          <li class="closed">Closed Now !</li>
        </ul>
      </div><!-- /.box-content -->
    </div><!-- /.box-imagebox -->
  </div><!-- /.imagebox style2 -->
</div><!-- /.col-sm-12 -->

app/views/restaurants/edit.html.erb
<section class="page-title parallax parallax1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumbs">
          <li>
            <%= link_to "Home", root_path %>
          </li>
          <li>
            <%= link_to "Restaurants", restaurants_path %>
          </li>
          <li>
           <p><%= @restaurant.name %></p>
          </li>
        </ul>
      </div><!-- /.col-md-12 -->
    </div><!-- /.row -->
  </div><!-- /.container -->
  <div class="overlay"></div>
</section><!-- /.page-title -->

<section class="flat-listing">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <form action="#" class="form-listing" method="get" accept-charset="utf-8">
          <div class="inner-box">
            <p>You make changes</p>
            <div class="clearfix"></div>
          </div>
        </form>

        <div class="row">
          <div class="col-md-12">
            <%= render "restaurants/form" %>
          </div>
        </div>
      </div><!-- /.col-md-12 -->
    </div><!-- /.row -->
  </div><!-- /.container -->
</section><!-- /.flat-listing -->

<div class="btn-more">
  <%= link_to "Back", @restaurant_path %>
</div>

app/views/restaurants/index.html.erb
<section class="page-title parallax parallax1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="page-title-heading">
          All Restaurant Listing
        </div>
        <ul class="breadcrumbs">
          <li>
            <%= link_to "Home", root_path %>
            <span class="arrow_right"></span>
          </li>
          <li>
            <p>All Restaurants </p>
            <span class="arrow_right"></span>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="overlay"></div>
</section>

<section class="flat-row flat-imagebox style3">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="filter-result style2">
          <div class="result">
            <%= @restaurant.count %> Results Found
          </div>
          <ul class="arrange">
            <li class="active">
              <span class="ti-view-grid"></span>
            </li>
            <li>
              <span class="ti-view-list"></span>
            </li>
          </ul>
        </div><!-- /.filter-result -->
      </div><!-- /.col-md-12 -->
    </div><!-- /.row -->
    <% unless @restaurant.blank? %>
      <% @restaurant.each do |x| %>

        <div class="col-sm-12">
          <div class="imagebox style2">
            <div class="box-imagebox">
              <div class="box-header">
                <div class="box-image">
                  <%= image_tag x.image.url unless x.image.blank? %>
                  <%= link_to "Preview", restaurant_path(id: x.id) %>
                </div>
              </div><!-- /.box-header -->
              <div class="box-content">
                <div class="box-title ad">
                  <%= link_to "#{x.name}", restaurant_path(id: x.id) %>
                </div>
                <ul class="rating">
                  <li><%= x.phone %></li>
                  <li><%= x.email %></li>
                </ul>
                <div class="box-desc">
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                </div>
                <ul class="location">
                  <li class="address"><span class="ti-location-pin"></span> <%= x.city %>, <%= x.state %></li>
                </ul>
              </div><!-- /.box-content -->
            </div><!-- /.box-imagebox -->
          </div><!-- /.imagebox style2 -->
        </div><!-- /.col-sm-12 -->

      <% end %>
    <% end %>

  </div>
</section>

app/views/restaurants/new.html.erb
<section class="page-title parallax parallax1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="page-title-heading">
          Add a Restaurant
        </div>
        <ul class="breadcrumbs">
          <li>
            <a href="index.html" title="">Home</a>
            <span class="arrow_right"></span>
          </li>
          <li>
            Add New Restaurant
          </li>
        </ul>
      </div><!-- /.col-md-12 -->
    </div><!-- /.row -->
  </div><!-- /.container -->
  <div class="overlay"></div>
</section><!-- /.page-title -->


<section class="flat-listing">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <form action="#" class="form-listing" method="get" accept-charset="utf-8">
          <div class="inner-box">
            <p>Add a new restaurant to the database</p>
            <div class="clearfix"></div>
          </div>
        </form>

        <div class="row">
          <div class="col-md-12">
            <%= render "restaurants/form" %>
          </div>
        </div>
      </div><!-- /.col-md-12 -->
    </div><!-- /.row -->
  </div><!-- /.container -->
</section><!-- /.flat-listing -->

app/views/restaurants/show.html.erb
<section class="page-title parallax parallax1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumbs">
          <li>
            <%= link_to "Home", root_path %>
          </li>
          <li>
            <%= link_to "Restaurants", restaurants_path %>
          </li>
          <li>
            <p><%= @restaurant.name %></p>

          </li>
        </ul>
      </div><!-- /.col-md-12 -->
    </div><!-- /.row -->
  </div><!-- /.container -->
  <div class="overlay"></div>
</section><!-- /.page-title -->

<section class="flat-title">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="title-left">
          <div class="box-title">
            <%= link_to @restaurant.name, restaurant_path %>
          </div><!-- /.box-title -->
          <ul class="box-address">
            <li class="address"><i class="fa fa-map-marker" aria-hidden="true"></i><%= @restaurant.street %> <%= @restaurant.suite %> | <%= @restaurant.city %>, <%= @restaurant.state %> <%= @restaurant.zip %></li>
            <li class="phone"><i class="fa fa-phone" aria-hidden="true"></i><%= @restaurant.phone %></li>
          </ul><!-- /.box-address -->
        </div><!-- /.title-left -->
      </div><!-- /.col-md-8 -->
    </div><!-- /.row -->
  </div><!-- /.container -->
</section><!-- /.flat-title -->

<section class="flat-row flat-explore-detail">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="text-box">
          <h3>Review</h3>
          <div class="text-desc">
            <!--review text goes here-->
          </div>
          <div class="btn-more">
            <%= link_to "Edit", edit_restaurant_path %>
          </div>
        </div>
      </div><!-- /.col-md-8 -->
      <div class="col-md-4">
        <div class="sidebar">
          <div class="box contact-box">
            <%= image_tag @restaurant.image.url unless @restaurant.image.blank? %>
          </div><!-- /#flat-map -->

          <div class="box contact-box">
            <ul class="contact-list">
              <li class="address"><i class="fa fa-map-marker" aria-hidden="true"></i><%= @restaurant.street %> <%= @restaurant.suite %> | <%= @restaurant.city %>, <%= @restaurant.state %> <%= @restaurant.zip %></li>
              <li><i class="fa fa-phone" aria-hidden="true"></i><%= @restaurant.phone %></li>
              <li><i class="fa fa-globe" aria-hidden="true"></i><%= @restaurant.email %></li>
            </ul>
          </div>
        </div>
      </div><!-- /.col-md-4 -->
    </div><!-- /.row -->
  </div><!-- /.container -->
</section><!-- /.flat-explore-detail <-->